### ISSUE TITLE
Crash on startup, metal hungry chest render error

### ISSUE THREAD

**Issue by sogortheogre** [T145/magistics#23]
---- Minecraft Crash Report ----
// Sorry :(

Time: 4/2/15 3:48 AM
Description: Initializing game

java.lang.NoClassDefFoundError: T145/magistics/client/renderers/tiles/TileChestHungryMetalRenderer
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:344)
	at cpw.mods.fml.common.ProxyInjector.inject(ProxyInjector.java:59)
	at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:492)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:492)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:204)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: T145.magistics.client.renderers.tiles.TileChestHungryMetalRenderer
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 35 more
Caused by: java.lang.NoClassDefFoundError: cpw/mods/ironchest/client/TileEntityIronChestRenderer
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 37 more
Caused by: java.lang.ClassNotFoundException: cpw.mods.ironchest.client.TileEntityIronChestRenderer
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 41 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:344)
	at cpw.mods.fml.common.ProxyInjector.inject(ProxyInjector.java:59)
	at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:492)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:492)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:204)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 181934968 bytes (173 MB) / 442855424 bytes (422 MB) up to 4281597952 bytes (4083 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 122 mods loaded, 122 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed
	FML{7.10.85.1291} [Forge Mod Loader] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed
	Forge{10.13.2.1291} [Minecraft Forge] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed
	AM2-Preloader{0.0.2} [AMCore] (minecraft.jar) Unloaded->Constructed
	appliedenergistics2-core{rv2-beta-8} [AppliedEnergistics2 Core] (minecraft.jar) Unloaded->Constructed
	Aroma1997Core{1.0.2.13} [Aroma1997Core] (Aroma1997Core-1.7.10-1.0.2.13.jar) Unloaded->Constructed
	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed
	<CoFH ASM>{000} [CoFH ASM Data Initialization] (minecraft.jar) Unloaded->Constructed
	MobiusCore{1.2.4} [MobiusCore] (minecraft.jar) Unloaded->Constructed
	NotEnoughItems{1.0.4.90} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.90-universal.jar) Unloaded->Constructed
	OpenEye{0.6} [OpenEye] (OpenEye-0.6-1.7.10.jar) Unloaded->Constructed
	ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core] (minecraft.jar) Unloaded->Constructed
	<DragonAPI ASM>{0} [DragonAPI ASM Data Initialization] (minecraft.jar) Unloaded->Constructed
	STPPlugin{} [ServerTools|Permission Plugin] (minecraft.jar) Unloaded->Constructed
	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) Unloaded->Constructed
	arsmagica2{1.4.0.008} [Ars Magica 2] (1.7.10_AM2-1.4.0.008.jar) Unloaded->Constructed
	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) Unloaded->Constructed
	ArmorStatusHUD{1.28} [ArmorStatusHUD] ([1.7.10]ArmorStatusHUD-client-1.28.jar) Unloaded->Constructed
	DamageIndicatorsMod{3.2.3} [Damage Indicators] ([1.7.10]DamageIndicatorsMod-3.2.3.jar) Unloaded->Constructed
	StatusEffectHUD{1.27} [StatusEffectHUD] ([1.7.10]StatusEffectHUD-client-1.27.jar) Unloaded->Constructed
	appliedenergistics2{rv2-beta-8} [Applied Energistics 2] (appliedenergistics2-rv2-beta-8.jar) Unloaded->Constructed
	ArchimedesShips{1.7.10 v1.7.1} [Archimedes' Ships] (ArchimedesShips-1.7.1.jar) Unloaded->Constructed
	Aroma1997CoreHelper{1.0.2.13} [Aroma1997Core|Helper] (Aroma1997Core-1.7.10-1.0.2.13.jar) Unloaded->Constructed
	CoFHCore{1.7.10R3.0.0RC4} [CoFH Core] (CoFHCore-[1.7.10]3.0.0RC4-204.jar) Unloaded->Constructed
	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1067-universal.jar) Unloaded->Constructed
	Forestry{3.5.0.481-unstable} [Forestry for Minecraft] (forestry_1.7.10-3.5.0.481-unstable.jar) Unloaded->Constructed
	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed
	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) Unloaded->Constructed
	Artifice{1.7.10R1.1.4} [Artifice] (Artifice-1.7.10-1.1.4-327.jar) Unloaded->Constructed
	Backpack{2.0.1} [Backpack] (backpack-2.0.1-1.7.x.jar) Unloaded->Constructed
	BetterChests{1.1.1.8} [BetterChests] (BetterChests-1.7.10-1.1.1.8.jar) Unloaded->Constructed
	betterstorage{0.12.0.124} [BetterStorage] (BetterStorage-1.7.10-0.12.0.124.jar) Unloaded->Constructed
	BiblioCraft{1.9.2} [BiblioCraft] (BiblioCraft[v1.9.2][MC1.7.10].jar) Unloaded->Constructed
	BiblioWoodsBoP{1.9} [BiblioWoods Biomes O'Plenty Edition] (BiblioWoods[BiomesOPlenty][v1.9].jar) Unloaded->Constructed
	BiblioWoodsForestry{1.7} [BiblioWoods Forestry Edition] (BiblioWoods[Forestry][v1.7].jar) Unloaded->Constructed
	BinnieCore{2.0-pre8} [Binnie Core] (binnie-mods-2.0-pre8.jar) Unloaded->Constructed
	Botany{2.0-pre8} [Botany] (binnie-mods-2.0-pre8.jar) Unloaded->Constructed
	ExtraBees{2.0-pre8} [Extra Bees] (binnie-mods-2.0-pre8.jar) Unloaded->Constructed
	ExtraTrees{2.0-pre8} [Extra Trees] (binnie-mods-2.0-pre8.jar) Unloaded->Constructed
	Genetics{2.0-pre8} [Genetics] (binnie-mods-2.0-pre8.jar) Unloaded->Constructed
	AWWayofTime{v1.3.1} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.10-1.3.1-7.jar) Unloaded->Constructed
	CarpentersBlocks{3.3.5} [Carpenter's Blocks] (Carpenter's Blocks v3.3.5 - MC 1.7.10.jar) Unloaded->Constructed
	ChickenChunks{1.3.4.16} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.16-universal(1).jar) Unloaded->Constructed
	chisel{1.5.7} [Chisel] (Chisel-1.7.10-1.5.7.jar) Unloaded->Constructed
	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed
	ThermalFoundation{1.7.10R1.0.0RC4} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.0.0RC4-58.jar) Unloaded->Constructed
	ThermalExpansion{1.7.10R4.0.0RC4} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.0RC4-135.jar) Unloaded->Constructed
	Waila{1.5.8} [Waila] (Waila-1.5.9_1.7.10.jar) Unloaded->Constructed
	TConstruct{1.7.10-1.8.2.build858} [Tinkers' Construct] (TConstruct-1.7.10-1.8.2a.jar) Unloaded->Constructed
	ForgeMultipart{1.1.1.320} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.1.320-universal.jar) Unloaded->Constructed
	ThaumicTinkerer{unspecified} [Thaumic Tinkerer] (ThaumicTinkerer-2.5-1.7.10-162.jar) Unloaded->Constructed
	MagicBees{1.7.10-2.1.22} [Magic Bees] (magicbees-1.7.10-2.1.22.jar) Unloaded->Constructed
	Mystcraft{0.11.0.00} [Mystcraft] (mystcraft-1.7.10-0.11.0.00.jar) Unloaded->Constructed
	MrTJPCoreMod{1.0.5.11} [MrTJPCore] (MrTJPCore-1.7.10-1.0.5.11-universal.jar) Unloaded->Constructed
	ProjRed|Core{4.5.13.65} [ProjectRed] (ProjectRed-1.7.10-4.5.13.65-Base.jar) Unloaded->Constructed
	DragonAPI{1.0} [DragonAPI] (DragonAPI 1.7.10 V6b.jar) Unloaded->Constructed
	ChromatiCraft{Alpha} [ChromatiCraft] (ChromatiCraft 1.7.10 V6b.jar) Unloaded->Constructed
	BuildMod{v1.0} [Build Mod] (CoroUtil-1.1.1.jar) Unloaded->Constructed
	CoroAI{v1.0} [CoroAI] (CoroUtil-1.1.1.jar) Unloaded->Constructed
	ExtendedRenderer{v1.0} [Extended Renderer] (CoroUtil-1.1.1.jar) Unloaded->Constructed
	ConfigMod{v1.0} [Extended Mod Config] (CoroUtil-1.1.1.jar) Unloaded->Constructed
	dynamictanks{1.0} [Dynamic Liquid Tanks 2.1] (dynamictanks-1.1.04.jar) Unloaded->Constructed
	EnderIO{1.7.10-2.2.8.349} [Ender IO] (EnderIO-1.7.10-2.2.8.349.jar) Unloaded->Constructed
	emashercore{1.3.0.1} [ET Resources] (EngineersToolbox-1.2.0.1-BETA.jar) Unloaded->Constructed
	emasherdefense{1.3.0.1} [ET Defense] (EngineersToolbox-1.2.0.1-BETA.jar) Unloaded->Constructed
	eng_toolbox{1.2.0.1} [Engineer's Toolbox] (EngineersToolbox-1.2.0.1-BETA.jar) Unloaded->Constructed
	gascraft{2.1.0.1} [GasCraft] (EngineersToolbox-1.2.0.1-BETA.jar) Unloaded->Constructed
	enhancedportals{3.0.10} [EnhancedPortals] (EnhancedPortals_1.7.10-universal-3.0.10.jar) Unloaded->Constructed
	extracells{2.2.55} [ExtraCells] (ExtraCells-1.7.10-2.2.55b85.jar) Unloaded->Constructed
	MetallurgyCore{4.0.4} [Metallurgy Core] (MetallurgyCore-1.7.10-4.0.4.18.jar) Unloaded->Constructed
	Metallurgy{4.0.6} [Metallurgy 4] (Metallurgy-1.7.10-4.0.6.80.jar) Unloaded->Constructed
	ExtraTiC{0.8.4} [ExtraTiC] (ExtraTiC-1.7.10-1.0.3.jar) Unloaded->Constructed
	ExtraUtilities{1.2.2} [Extra Utilities] (extrautilities-1.2.2.jar) Unloaded->Constructed
	farlanders{1.2b} [The Farlanders] (farlanders-1.7.10-v1.2b.jar) Unloaded->Constructed
	FlatSigns{2.1.0.19} [Flat Signs] (FlatSigns-1.7.10-universal-2.1.0.19.jar) Unloaded->Constructed
	ForbiddenMagic{1.7.10-0.561} [Forbidden Magic] (Forbidden Magic-1.7.10-0.561.jar) Unloaded->Constructed
	ganysend{1.8.8} [Gany's End] (Ganys End-1.8.8.jar) Unloaded->Constructed
	ganysnether{1.7.8} [Gany's Nether] (Ganys Nether-1.7.8.jar) Unloaded->Constructed
	ganyssurface{1.9.5} [Gany's Surface] (Ganys Surface-1.9.5.jar) Unloaded->Constructed
	HopperDuctMod{1.3.2} [Hopper Ducts] (hopperductmod-1.7.10-1.3.2.jar) Unloaded->Constructed
	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) Unloaded->Constructed
	JABBA{1.2.0b} [JABBA] (Jabba-1.2.1_1.7.10.jar) Unloaded->Constructed
	magicalcrops{1.7.2 - 0.1 ALPHA} [Magical Crops] (magicalcrops-1.7.10_0.1.jar) Unloaded->Constructed
	Magistics{8.0.0} [Magistics] (Magistics-1.7.10-0.7.6.jar) Unloaded
	MineTweaker3{3.0.9B} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.9C.jar) Unloaded
	NEIAddons{1.12.5.17} [NEI Addons] (neiaddons-mc1710-1.12.5.17.jar) Unloaded
	NEIAddons|Botany{1.12.5.17} [NEI Addons: Botany] (neiaddons-mc1710-1.12.5.17.jar) Unloaded
	NEIAddons|Forestry{1.12.5.17} [NEI Addons: Forestry] (neiaddons-mc1710-1.12.5.17.jar) Unloaded
	NEIAddons|CraftingTables{1.12.5.17} [NEI Addons: Crafting Tables] (neiaddons-mc1710-1.12.5.17.jar) Unloaded
	NEIAddons|ExNihilo{1.12.5.17} [NEI Addons: Ex Nihilo] (neiaddons-mc1710-1.12.5.17.jar) Unloaded
	neiintegration{1.0.7} [NEI Integration] (NEIIntegration-MC1.7.10-1.0.7.jar) Unloaded
	NetherOres{1.7.10R2.3.0RC3} [Nether Ores] (NetherOres-[1.7.10]2.3.0RC3-84.jar) Unloaded
	ObsidiPlates{3.0.0.18} [ObsidiPlates] (ObsidiPlates-1.7.10-universal-3.0.0.18.jar) Unloaded
	MapWriter{2.1.2} [MapWriter] (Opis-1.2.4a_1.7.10.jar) Unloaded
	Opis{1.2.4} [Opis] (Opis-1.2.4a_1.7.10.jar) Unloaded
	harvestcraft{1.7.10g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10g.jar) Unloaded
	planetguyLib{1.5} [planetguyLib] (PlanetguyLib-1.5.jar) Unloaded
	RandomThings{2.2.4} [Random Things] (RandomThings-2.2.4.jar) Unloaded
	RotaryCraft{Gamma} [RotaryCraft] (RotaryCraft 1.7.10 V6b.jar) Unloaded
	ReactorCraft{beta} [ReactorCraft] (ReactorCraft 1.7.10 V6a.jar) Unloaded
	JAKJ_RedstoneInMotion{2.5.2} [Remain In Motion] (RemainInMotion-2.5.3.jar) Unloaded
	RIO{2.1} [RemoteIO] (RemoteIO-1.7.10-2.1.B0-universal.jar) Unloaded
	Revamp{1.3.0} [Revamp] (Revamp-1.3.0.jar) Unloaded
	Roguelike{1.3.6} [Roguelike Dungeons] (roguelike-1.7.10-1.3.6.jar) Unloaded
	ServerTools{1.7.10-2.2.0.79} [ServerTools] (ServerTools-CORE-1.7.10-2.2.0.79.jar) Unloaded
	ServerTools-PERMISSION{1.7.10-2.2.1.7} [ServerTools Permission] (ServerTools-PERMISSION-1.7.10-2.2.1.7.jar) Unloaded
	StevesFactoryManager{A93} [Steve's Factory Manager] (StevesFactoryManagerA93.jar) Unloaded
	ThaumicExploration{0.6.0} [Thaumic Exploration] (ThaumicExploration-1.7.10-1.1-37.jar) Unloaded
	TMechworks{0.2.13.96} [Tinkers' Mechworks] (TMechworks-1.7.10-0.2.13.96.jar) Unloaded
	torchLevers{1.4.1} [Torch Levers] (TorchLeversV1.4.1.jar) Unloaded
	Translocator{1.1.1.14} [Translocator] (Translocator-1.7.10-1.1.1.14-universal.jar) Unloaded
	TwilightForest{2.3.3} [The Twilight Forest] (twilightforest-1.7.10-2.3.3.jar) Unloaded
	UtilityMobs{3.1.1} [Utility Mobs] (UtilityMobs-1.7.10-3.1.1.jar) Unloaded
	weaponmod{v1.14.3} [Balkon's WeaponMod] (weaponmod-1.14.3.jar) Unloaded
	weather2{v2.3.6} [weather2] (Weather-2.3.7.jar) Unloaded
	witchery{0.22.0} [Witchery] (witchery-1.7.10-0.22.0.jar) Unloaded
	WR-CBE|Core{1.4.1.9} [WR-CBE Core] (WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded
	WR-CBE|Addons{1.4.1.9} [WR-CBE Addons] (WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded
	WR-CBE|Logic{1.4.1.9} [WR-CBE Logic] (WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded
	McMultipart{1.1.1.320} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.1.320-universal.jar) Unloaded
	aobd{2.4.0} [Another One Bites The Dust] (AOBD-2.4.0.jar) Unloaded
	ForgeMicroblock{1.1.1.320} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.1.320-universal.jar) Unloaded
	AE2 Version: beta rv2-beta-8 for Forge 10.13.2.1230
	CoFHCore: -[1.7.10]3.0.0RC4-204
	Mantle Environment: Environment healthy.
	ThermalFoundation: -[1.7.10]1.0.0RC4-58
	ThermalExpansion: -[1.7.10]4.0.0RC4-135
	TConstruct Environment: Environment healthy.
	Launched Version: 1.7.10-Forge10.13.2.1291
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 670/PCIe/SSE2 GL version 4.4.0, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by T145** [comment]
This is resolved. Wait on a release; I'll upload one once I'm on decent wifi.

**Comment by sogortheogre** [comment]
Gotcha, I always forget to look at closed tickets and only ever check open
ones >.>. <3

**Comment by T145** [comment]
Mogor's siblings always miss things; it's alright :P
